### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-validate#1]
Add badges similar to [flip-remote](https://github.com/arshadkazmi42/flip-remote#flip-remote-octocat)

**Comment by ramstore07** [comment]
I’ll take a look tomorrow:)

**Comment by arshadkazmi42** [comment]
@ramstore07 Are you working on this? Let me know if you need any help with this

**Comment by l92s** [comment]
Hello, do you still need help with this @arshadkazmi42 ?

**Comment by arshadkazmi42** [comment]
@sianlouisa Yes. It is still open. We have couple of badges which are not added yet

**Comment by l92s** [comment]
OK, I can take a look at adding the missing badges now :) I am assuming the licence and downloads badges are the ones your still require?

**Comment by arshadkazmi42** [comment]
NPM VERSION
LICENSE
DOWNLOADS
