### ISSUE TITLE
remove yarn.lock file

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-validate#8]
We have package-lock  and yarn lock files we need only one.
Lets remove yarn.lock file

**Comment by danielotieno** [comment]
Hey @arshadkazmi42  I can take this one

**Comment by arshadkazmi42** [comment]
Yes. Go ahead

**Comment by danielotieno** [comment]
Looks like @majordwarf did it

**Comment by arshadkazmi42** [comment]
> Looks like @majordwarf did it

Yes. If interested in more, you can also look into other issues we have

**Comment by danielotieno** [comment]
Sure
